## General pipeline parameters:

# working directory (required; cannot be an empty string)
workdir: "PSQAN/test_output"

# prefix of all output files (required; cannot be an empty string)
sample_name: "testData"

# sqanti "classification.txt" file (required)
sqanti_class: "PSQAN/test_data/sqanti_classification.txt"

# sqanti corrected.fasta file (required)
sqanti_fasta: "PSQAN/test_data/sqanti_corrected.fasta"

# gene of interest (optional)
# leave as empty string ("") if not using
# multiple genes can be input separated by ";", but it is recommended to use PSQAN with a single genes
gene_ids: "ENSG00000TEST"

######################################################
# transcript thresholds for filtering
# only transcripts with >= thresholds will be retained
######################################################

# does your sqanti file has abundences of more than one sample?
multisample: "yes"

# threshold of NFLR (if one sample) or NFLR_mean across samples (if multisample); default = 0.3
NFLR_mean: 0.3

# threshold of "normalised expression per sample"; default = 0
# Not used if only one sample
NFLR_perSample: 0

# minimum number of samples (%) which should pass NFLR threshold; default = 0
# Not used if only one sample
min_sample_perc: 8
