$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

properties:
  workdir:
    type: string
    minLength: 1

  sample_name:
    type: string
    default: "sample"
    minLength: 1

  sqanti_class:
    type: string

  sqanti_fasta:
    type: string

  gene_ids:
    type: string
    default: ""

  multisample:
    type: string
    enum: ["yes", "no"]
    minLength: 1
    default: "no"

  NFLR_mean:
    type: number
    default: 0.3

  NFLR_perSample:
    type: number
    default: 0

  min_sample_perc:
    type: number
    default: 0


required:
  - workdir
  - sqanti_class
  - sqanti_fasta
