name: Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [ main ]


jobs:
  Unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Mamba env setup
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: psqan_venv
          environment-file: environment.yml

      - name: run tests
        run: |
          Rscript tests/testthat.R
